### ISSUE TITLE
[D+] Add missing Chairmen, Vice-chairs, to database

### ISSUE THREAD

**Issue by ipgray** [medea-project/ipcc-database#56]
In ipcc-database folder, we already have a file at https://github.com/medea-project/ipcc-database/blob/master/data/chairman_offices.csv that includes 75 chairmen and vice-chairs over the 5 ARs. 

There are roughly 50 names that are missing from the chairmen/vice-chair roles. The full table is below, including also all the TSU heads, who I would also like to add into the database. Please find the missing names and add those lines into the existing chairmen_offices.csv file.

![image](https://cloud.githubusercontent.com/assets/7768944/5300647/34ae96c0-7bd2-11e4-8716-67a3825c4c9d.png)

**Comment by legaultpierre** [comment]
@ipgray could you send me a csv version of the full table?
Furthermore, are the chairmen related to institutions or only to country?

**Comment by ipgray** [comment]
@legaultpierre just sent you the .csv
