### ISSUE TITLE
[D+] Update AR5 authors: WGI, WGII, WGIII

### ISSUE THREAD

**Issue by eric-brechemier** [medea-project/ipcc-database#58]
Several issues are related to invalid, missing or out of date information for AR5:

  * #45
  * #42
  * #36
  * #21

I have completed the acquisition of latest author data for AR5 in ipcc-fact-checking project, and will track the progress of the insertion of this data in ipcc-database as a full replacement to the existing AR5 data in this ticket.

**Comment by ipgray** [comment]
booyah

**Comment by tommv** [comment]
This is also a huge one!
Well done Pierre:
https://www.youtube.com/watch?v=LlhKZaQk860


On 01/04/15 17:31, legaultpierre wrote:
>
> Closed #58 <https://github.com/medea-project/ipcc-database/issues/58>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/medea-project/ipcc-database/issues/58#event-270753057>.
>


-- 
--------------------------------------------------------------------------
Tous les courriers électroniques émis depuis la messagerie de Sciences Po 
doivent respecter les conditions d'usage.
Pour les consulter rendez-vous sur :
http://www.sciencespo.fr/ressources-numeriques/fr/content/regles-de-confidentialite

**Comment by legaultpierre** [comment]
Ahah I can't deny I'm relieved now this one is done :)

**Comment by eric-brechemier** [comment]
@legaultpierre do you plan to merge AR5_extras into the master branch now that you have fixed this issue?

**Comment by legaultpierre** [comment]
Hi @eric-brechemier , this is already done, we just decided not to delete the AR5_extras branch yet

**Comment by eric-brechemier** [comment]
OK, thanks for the clarification. I got confused by git which does not report the branch as merged.
