### ISSUE TITLE
R. Allan (CSIRO, AR3) is not R. Allan (University of Reading, AR4)

### ISSUE THREAD

**Issue by eric-brechemier** [medea-project/ipcc-database#61]
All the contributions of 'R. Allan' in AR3 and AR4 have been attributed to 'Richard Allan' in the database.

The 'R. Allan' in AR4 is:

> ALLAN, Richard
Environmental Systems Science Centre, University of Reading
UK 

Source: annex II
http://www.ipcc.ch/publications_and_data/ar4/wg1/en/annexessannex-ii.html

**But** according to [this comprehensive list of authors from CSIRO who contributed to IPCC reports from AR1 to AR4](http://www.csiro.au/Organisation-Structure/Divisions/Marine--Atmospheric-Research/NobelPeacePrizeWinners.aspx), 'R. Allan' is actually 'Rob Allan (former CSIRO)'.

Richard Allan
http://www.reading.ac.uk/search/search-staff-details.aspx?id=5869

Rob Allan
http://www.colby.edu/ichm/ichm_bios/allan.htm

**Comment by ipgray** [comment]
@legaultpierre way to kill the easy ones. all of our issues now fit on one Github page. yay.
