### ISSUE TITLE
Institution redundancy: Australian Bureau of Meteorology & Bureau Of Meteorology

### ISSUE THREAD

**Issue by legaultpierre** [medea-project/ipcc-database#63]

**Comment by ipgray** [comment]
@legaultpierre; hmmm. these ones are pains in the ass. I guess make it Bureau of Meteorology. That's how they call themselves and we've tried as much as possible to keep the actors own definition of themselves in this database. The country affiliation will make it clear enough about the Australia bit.

**Comment by legaultpierre** [comment]
Done
