### ISSUE TITLE
Missing country groups for Bahamas, New Caledonia, Niger

### ISSUE THREAD

**Issue by eric-brechemier** [medea-project/ipcc-database#72]
I noticed this issue because the total number of participations by country group only showed a decreased and no corresponding increase when the participation for Fiji was reassigned to New Caledonia.

I wrote a SQL query which lists all countries not assigned to any country group for each type of grouping:

```sql
SELECT DISTINCT groups.type, countries.*
FROM groups, countries
WHERE (countries.id, groups.type) NOT IN (
  SELECT DISTINCT groupings.country_id, groups.type
  FROM groupings, groups
)
;
```

```
+------+-----+------+---------------+
| type | id  | code | name          |
+------+-----+------+---------------+
| GEO  | 124 | BHS  | Bahamas       |
| WMO  | 124 | BHS  | Bahamas       |
| ECO  | 124 | BHS  | Bahamas       |
| CLI  | 124 | BHS  | Bahamas       |
| GEO  | 125 | NCL  | New Caledonia |
| WMO  | 125 | NCL  | New Caledonia |
| ECO  | 125 | NCL  | New Caledonia |
| CLI  | 125 | NCL  | New Caledonia |
| GEO  | 126 | NER  | Niger         |
| WMO  | 126 | NER  | Niger         |
| ECO  | 126 | NER  | Niger         |
| CLI  | 126 | NER  | Niger         |
+------+-----+------+---------------+
12 rows in set (0.95 sec)
```

**Comment by ipgray** [comment]
@eric-brechemier merci d'avoir pointer ces manques; @legaultpierre, voila les codes a ajouter a ces pays.

Bahamas:
WMO = NAC (North America, Central America and the Caribbean)
CLI = AOSIS (Alliance of Small Island States)
CLI = NA1 (Non-Annex I)
GEO = GRULAC (Latin American and Caribbean Group)
ECO = DdC (Developed Countries)

New Caledonia = territory of France (so all the country groupings are the same as France)

Niger:
WMO = AFR (Africa)
GEO = AG (Africa Group)
CLIM = NA1 (Non-Annex 1)
ECO = LDCs (Least Developed Countries)
ECO = DgE (Developing Economies)

**Comment by eric-brechemier** [comment]
@legaultpierre I reopen the issue: 'New Caledonia' still has no country group.

@ipgray: I don't think that copying all country groups of France for 'New Caledonia' would make sense either, if it is what you had in mind:

```sql
mysql> SELECT DISTINCT 'New Caledonia' AS name, groupings.symbol, groups.name FROM groups JOIN groupings ON groups.symbol = groupings.symbol JOIN countries ON groupings.country_id = countries.id WHERE countries.name = 'France' ORDER BY groupings.symbol;
+---------------+--------+---------------------------------------------------------------+
| name          | symbol | name                                                          |
+---------------+--------+---------------------------------------------------------------+
| New Caledonia | A1     | Annex I                                                       |
| New Caledonia | AOGCM  | Countries with Coupled Atmosphere-Ocean Global Climate Models |
| New Caledonia | DdC    | Developed Countries                                           |
| New Caledonia | EU     | European Union                                                |
| New Caledonia | EUR    | Europe                                                        |
| New Caledonia | G20    | G20                                                           |
| New Caledonia | G8     | G8                                                            |
| New Caledonia | OCDE   | OECD                                                          |
| New Caledonia | OIF    | Organisation Internationale de la Francophonie                |
| New Caledonia | WEOG   | Western Europe and Other States Group                         |
+---------------+--------+---------------------------------------------------------------+
10 rows in set (0.01 sec)
```

**Comment by ipgray** [comment]
@eric-brechemier, i agree, this is a tricky one. generally, we shouldn't count New Caledonia as a country, since it's just an overseas territory of France; but, with the politics of climate change and the politics of the IPCC, since this author insisted on being identified as New Caledonia, we're including them. As far as the groupings to which they belong...they would normally fall under the same umbrellas as France.

I'm sorry, but perhaps you had a different idea? if so, I'm all ears.

**Comment by eric-brechemier** [comment]
@ipgray this is tricky, I agree. Technically, since 'New Caledonia' is [not an IPCC Member](http://www.ipcc.ch/pdf/ipcc-principles/ipcc-principles-elections-rules.pdf#page=8), the participation should be listed as 'France'.

This would be consistent with how we treat the participations for 'Hong Kong' in AR5: they are listed as 'China', e.g. AR5 WGIII Ch12, LA from 'City University of Hong Kong', 'China'.

This would also be consistent with how we treated 'Scotland' as an alias for 'United Kingdom':
https://github.com/medea-project/ipcc-database/blob/master/data/country_aliases.csv#L11

On the other hand, I am reluctant to losing this information. If New Caledonia [chooses to become an independent state by referendum](https://en.wikipedia.org/wiki/Noum%C3%A9a_Accord), this participation could be interpreted as a sign of its independent activity within the IPCC. But maybe it is too soon for that?

If you choose to keep 'New Caledonia' separated, however, I think that it should not be treated like an alias for France in terms of country groupings, but as an independent territory with its own country groups.

Notably, the [WMO group of 'New Caledonia' would be 'South-West Pacific'](https://www.wmo.int/cpdb/dashboard/new-caledonia) (SWP), not 'Europe' (EUR).

**Comment by ipgray** [comment]
@eric-brechemier, all good points. Although I loathe removing the voice of independence from our database (I do think it's too early to think that it's going to be an independent state), I guess I favor consistency at this point, and expediency. Since you reminded me of our previous treatments of this issue, we will stick to what we did before. 

@legaultpierre, please change the "New Caledonia" participation to "France". Our argument is fairly straightforward. We are only counting countries recognized by the UN at the time of our project. 

This will drop down our participating countries to 116. And 117 with Mali among the Chairmen and Vice-Chairs. I will explain this to Samuel Bianchini.
